django_unchained/django_unchained/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('meuapp/', include('meuapp.urls')),
    path('admin/', admin.site.urls),
]

django_unchained/meuapp/urls.py
from django.urls import path
from . import views

app_name = 'meuapp'

urlpatterns = [
    path('article/', views.list, name="article_list"),
    path('article/create', views.create, name="article_create"),
    path('article/<int:article_id>', views.read, name="article_read"),
    path('article/delete/<int:article_id>', views.delete, name='article_delete'),
    path('article/update/<int:article_id>', views.update, name="article_update"),
]

django_unchained/meuapp/models.py
from django.db import models

# Create your models here.

django_unchained/meuapp/models/account.py
from meuapp.models.base import BaseModel
from django.db import models
from django.contrib.auth.models import User

class Account(BaseModel):
    owner = models.ManyToManyField(User, verbose_name= 'Account Owner')
    description = models.CharField(max_length=200, help_text='Description for your account')
    number = models.CharField(max_length=20, help_text='Insert your account number here.')
    balance = models.FloatField(default=0, help_text='Insert your initial balance.')
 
    class Meta:
        abstract = False

    def __str__(self):
        return f'{self.number}: {self.description} - {self.balance}'

    def update_balance(self, value):
        try:
            self.balance = self.balance + float(value)
            return True
        except:
            return False

    def get_balance(self):
        return self.balance

#aaa

django_unchained/meuapp/models/article.py
from meuapp.models.base import BaseModel
from django.db import models
from meuapp.models.reporter import Reporter
from meuapp.models.magazine import Magazine

class Article(BaseModel):
    title = models.CharField(max_length=100, verbose_name='Article title', help_text='Insert the article title')
    pub_date = models.DateTimeField(verbose_name='Publication date', help_text='Insert the publication date time')
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)
    magazines = models.ManyToManyField(Magazine, verbose_name='Magazines', help_text='Select magazines')

    class Meta:
        abstract = False

    def __str__(self):
        return self.title

    #aaa

django_unchained/meuapp/models/base.py
from django.db import models

class BaseModel(models.Model):
    class Meta:
        abstract = True
        app_label = 'meuapp'

    #aaa

django_unchained/meuapp/models/magazine.py
from meuapp.models.base import BaseModel
from django.db import models

class Magazine(BaseModel):
    name = models.CharField(max_length=100, verbose_name='Magazine name', help_text='Insert the magazine name')
    edition = models.IntegerField(verbose_name='Magazine edition number', help_text='Insert the magazine number')
    
    class Meta:
        abstract = False
    
    def __str__(self):
        return f'{self.name}: {self.edition}'
    
    #aaa

django_unchained/meuapp/models/passport.py
from meuapp.models.base import BaseModel
from meuapp.models.person import Person
from django.db import models

class Passport(BaseModel):
    number = models.CharField(max_length=10, verbose_name='Passport Number', help_text='Insert your passport number')
    issue_date = models.DateField(verbose_name='Issue Date', help_text='Insert the issue date of the passport.')
    expiration_date = models.DateField(verbose_name='Expiration Date', help_text='Insert the expiration date')
    person = models.OneToOneField(Person, on_delete=models.CASCADE, primary_key=True)

    class Meta:
        abstract = False

    def issue_passport(self, issue_date, expiration_date):
        pass
#aaa

django_unchained/meuapp/models/person.py
from meuapp.models.base import BaseModel
from django.db import models

class Person(BaseModel):
    name = models.CharField(max_length=100, verbose_name='Full Name', help_text='Insert your name')
    birth_date = models.DateField(verbose_name='Birth Date', help_text='Insert your birth date')
    cpf = models.CharField(max_length=11, verbose_name='CPF Number', help_text='Insert your CPF number')
    
    class Meta:
        abstract = False

    def check_visa(self, place, date):
        #TODO: Implementar metodo para verificação do visto
        pass
    
    def __str__(self):
        return self.name

#aaa

django_unchained/meuapp/models/reporter.py
from meuapp.models.base import BaseModel
from django.db import models

class Reporter(BaseModel):
    name = models.CharField(max_length=100, verbose_name='Full Name', help_text='Insert the full name')
    email = models.EmailField(verbose_name='Email', help_text='Insert the professional email')
    cpf = models.CharField(max_length=11, verbose_name='Insert the CPF Number', help_text='Insert your CPF number')

    class Meta:
        abstract = False
    
    def __str__(self):
        return self.name
    #aaa

django_unchained/meuapp/forms/article_form.py
from django import forms
from django.forms import TextInput
from meuapp.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args,**kwargs)
        for new_field in self.visible_fields():
            new_field.field.widget.attrs['class'] = 'form-control'

django_unchained/meuapp/forms/contact_form.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=200, label="Email subject", help_text='Insert your subject', initial='Subject')
    name = forms.CharField(max_length=100, label="Full name", help_text="Insert your full name")
    sender = forms.EmailField(label='Email address', help_text="Insert your email address")
    cc = forms.BooleanField(required=False)
    message = forms.CharField(widget=forms.Textarea, help_text="Insert your message.")

django_unchained/django_unchained/views.py
from django.shortcuts import render


def index(request):
    context = {"nome": "Guilherme"}
    return render(request, 'content.html', context)

django_unchained/meuapp/views.py
from django.shortcuts import render

# Create your views here.

django_unchained/meuapp/views/article.py
from django.shortcuts import render, get_object_or_404, redirect
from meuapp.models.article import Article
from meuapp.forms.article_form import ArticleForm


def list(request):
    articles = Article.objects.all()
    context = {"articles": articles}
    return render(request, "meuapp/article_list.html", context)

def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('meuapp:article_list')
    else:
        form = ArticleForm()
    context = {"form": form}
    return render(request, "meuapp/article_create.html", context)

def delete(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    try:
        article.delete()
        # TODO: message
        return redirect('meuapp:article_list')
    except:
        context = {}
        # TODO: message
        return render(request, "meuapp/article_list", context)

def read(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    context = {"article": article,}
    return render(request, "meuapp/article_read.html", context)

def update(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    try:
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                # TODO: message
                return redirect('meuapp:article_list')
        else:
            form = ArticleForm(instance=article)
            context = {"form":form,
            "article_id":article_id}
            return render(request, "meuapp/article_edit.html", context)
    except:
        # TODO: message
        return redirect(request, "meuapp:article_list")

django_unchained/meuapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Django Unchained</title>
  </head>
  <body>
    {% block menu %}

    {% endblock %}
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

django_unchained/meuapp/templates/meuapp/article_create.html
{% extends "content.html" %}

{% block content %}
    <h1>Article edit</h1>
    <div class="col-12">
        <form action="{% url 'meuapp:article_create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-primary">Create</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>
{% endblock %}

django_unchained/meuapp/templates/meuapp/article_edit.html
{% extends "content.html" %}

{% block content %}
    <h1>Article edit</h1>
    <div class="col-12">
        <form action="{% url 'meuapp:article_update' article_id %}" method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>
{% endblock %}

django_unchained/meuapp/templates/meuapp/article_list.html
{% extends "content.html" %}

{% block content %}
    {% if message %}
        <div class="alert alert-primary" role="alert">
            A simple primary alert—check it out!
        </div>
    {% endif%}
    
    {% if articles %}
    <h1>Article list</h1>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Publication Date</th>
            <th scope="col">Reporter</th>
            <th scope="col">Magazine</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td>{{article.title}}</td>
            <td>{{article.pub_date|date:"d/M/Y H:i"}}</td>
            <td>{{article.reporter}}</td>
            <td>{{article.magazines.all|join:", "}}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'meuapp:article_read' article.id %}" role="button">
                    <span class="text-light text-center">
                        <i class="fas fa-eye"></i>
                    </span>
                </a>
                <a class="btn btn-warning" href="{% url 'meuapp:article_update' article.id %}" role="button">
                    <span class="text-light text-center">
                        <i class="far fa-edit"></i>
                    </span>
                </a>
                <a class="btn btn-danger" href="{% url 'meuapp:article_delete' article.id %}" role="button">
                    <span class="text-light text-center">
                        <i class="far fa-trash-alt"></i>
                    </span>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-success" href="{% url 'meuapp:article_create' %}" role="button">
        <span class="text-light text-center">
            + Add a new Article
        </span>
    </a>
    {% else %}
        <h2>No articles to show</h2>
    {% endif %}
{% endblock %}

django_unchained/meuapp/templates/meuapp/article_read.html
{% extends "content.html" %}

{% block content %}

    <h1>Article list</h1>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Field</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="col">Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th scope="col">Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th scope="col">Publication Date</th>
                <td>{{ article.pub_date|date:"d/M/Y H:i" }}</td>
            </tr>
            <tr>
                <th scope="col">Reporter</th>
                <td>{{ article.reporter }}</td>
            </tr>
            <tr>
                <th scope="col">Magazines</th>
                <td>{{ article.magazines.all|join:", " }}</td>
            </tr>
        </tbody>
    </table>
    <a class="btn btn-primary" href="{% url 'meuapp:article_list' %}" role="button">
        <span class="text-light text-center">
            Back
        </span>
    </a>
{% endblock %}

django_unchained/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/f3c400cddf.js" crossorigin="anonymous"></script>

    <title>Django Unchained</title>
  </head>
  <body>
    {% block menu %}

    {% endblock %}
    <div class="container">
      <div class="row">
    {% block content %}

    {% endblock %}
      </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

django_unchained/templates/content.html
{% extends 'menu.html' %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Olá, {{ nome }}!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
{% endblock %}

django_unchained/templates/menu.html
{% extends 'base.html'%}
{% block menu %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Django Unchained</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Article</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'meuapp:article_list' %}">Articles List</a>
                        <a class="dropdown-item" href="{% url 'meuapp:article_create' %}">Create an Article</a>
                    </div>
                </li>
            </ul>
        
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        </div>
    </nav>
{% endblock %}